<?php require_once __DIR__ . '/../contoler/db.php';
if (!isset($_SESSION['uid'])) {
    header("Location: ../public/login.php");
    exit();
}
if ($_SESSION['role'] != 'faculty') {
    header("Location: ../public/home.php");
    exit();
}
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Faculty Profile</title>
    <link href="../CSS/index.css" rel="stylesheet" type="text/css"/>
</head>
<body> 
<form id="form1">
    <div id="Panel1" class="topbar">
        <img id="logo" class="logo" alt="Project-Gate Logo" src="../Admin/img/logo_admin.png" />
        <span style="float: right; margin: 60px 40px 0 0; font-size: 18px; font-weight: bold; color: green;">Faculty: [Username]</span>
        <a id="hidash" class="nav-link" href="/Faculty/dashboard.aspx">Dashboard</a>
        <a id="hlhome" class="nav-link" href="/Faculty/home.aspx">Home</a>
        <a id="hllout" class="nav-link" href="#">Log Out</a>
    </div>
    <div id="pnsidebar" class="sidebar">
        <a id="lbtndash" href="dashboard.php">Dashboard</a>
        <a id="Ibtnproject" href="reviewproject.php">Student Projects</a>
        <a id="Ibtnfact" href="profile.php" style="font-weight:bold; color:#ffeb3b;">Profile</a>
        <a id="Ibtnresult" href="grad.php">Student Results</a>
        <a id="Ibtnupwd" href="pwdchange.php">Password Change</a>
        <a id="Ibtlout" href="../public/logout.php">Log Out</a>
    </div>
    <div id="pnicontant" class="contant">
        <div class="page-header">
            <div><h1>Faculty Profile</h1><p>Manage your faculty profile and information.</p></div>
        </div>
        <div class="content-card">
            <h2>Faculty Information</h2><p>View and manage your faculty information.</p>
            <div class="form-body">
                <div class="form-group">
                    <label id="Iblfname" class="form-label">First Name</label>
                    <input type="text" id="txtfname" class="form-input" required />
                </div>
                <div class="form-group">
                    <label id="Ibliname" class="form-label">Last Name</label>
                    <input type="text" id="txtiname" class="form-input" required />
                </div>
                <div class="form-group">
                    <label id="lblSubject" class="form-label">Subject</label>
                    <select id="ddlSubject" class="form-input" required>
                        <option value="">Select Subject</option>
                        <!-- Options generated by backend -->
                    </select>
                    <br /><br />
                    <span id="lblMsg" style="font-weight:bold;"></span>
                    <br /><br />
                    <button type="submit" id="btnUpdate" class="btn btn-primary">Update Profile</button>
                </div>
            </div>
        </div>
    </div>
</form>
</body>
</html>